name: "Send Email Notification"

on:
    workflow_dispatch:


jobs:
    send_email:
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v4

            - name: "Setup Python"
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: "Install dependencies"
              run: |
                python -m pip install --upgrade pip
                

            - name: "Send Email"
              run: python script.py
              env:
                WORKFLOW_NAME: ${{ github.workflow }}
                REPO_NAME: ${{ github.repository }}
                SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD}}
                SENDER_EMAIL: ${{ secrets.SENDER_EMAIL}}
                RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL}}
                RUN_ID: ${{ github.run_id }}